name = input("Digite seu primeiro nome: ")
idade = int(input("Digite sua idade: "))
altura = float(input("Digite sua altura: "))
print(f"Seu nome é {name}, sua idade é {idade} anos e sua altura é {altura:.2f}")
print(f"{name} é definitivamente idoso") if idade >= 60 else print(f"{name} é jovem")
print(name)
